name: worksheet_wizard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.0.15
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
