name: worksheet_wizard
description: "Worksheet creator application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.0.15
  firebase_core: 3.13.0
  firebase_auth: 5.5.2
  flutter_math_fork: ^0.7.2
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/WorksheetWizardIcon.png"

flutter:
  uses-material-design: true
